---
services:
  backend:
    image: hiteshpatil989/employee-tracker-backend:latest
    container_name: produx-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: "7d"
      NODE_ENV: "production"
      FRONTEND_URL: "http://18.209.47.148"
      PORT: "5000"

  frontend:
    image: hiteshpatil989/employee-tracker-frontend:latest
    container_name: produx-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
