name: code quality

on:
  workflow_dispatch: 

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Install backend Dependencies
        run: |
          cd backend 
          npm install
      
      - name: Lint Frontend Code
        run: |
          cd frontend
          npx eslint .
      
      - name: Lint backend Code
        run: |
          cd backend
          npx eslint .

      
        