name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🚀 Setting up EC2..."

            sudo apt-get update
            sudo apt-get install -y docker.io docker-compose-v2

            sudo usermod -aG docker ubuntu

            mkdir -p /home/ubuntu/devops

      - name: Copy docker-compose file
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: docker-compose.yml
          target: /home/ubuntu/devops

      - name: Deploy Application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🚀 Running App..."

            cd /home/ubuntu/devops

            echo "📥 Pull latest images..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/employee-tracker-backend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/employee-tracker-frontend:latest

            echo "🛑 Stopping old containers..."
            docker compose down

            echo "🚀 Starting new containers..."
            docker compose up -d

            echo "🧹 Cleaning unused images..."
            docker image prune -f

            echo "✅ Deployment completed!"